
CREATE TABLE `dept` (
  `department_id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  create_date DATETIME NOT NULL DEFAULT NOW(),
  update_date DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`department_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8